# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{am-sbdb}
  s.version = "0.0.10.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Denis Knauf}]
  s.date = %q{2011-08-24}
  s.description = %q{Simple Ruby Berkeley DB wrapper library for bdb.}
  s.email = %q{Denis.Knauf@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "AUTHORS",
    "README.md",
    "VERSION",
    "lib/sbdb.rb",
    "lib/sbdb/cursor.rb",
    "lib/sbdb/db.rb",
    "lib/sbdb/environment.rb",
    "lib/sbdb/transaction.rb",
    "lib/sbdb/weakhash.rb"
  ]
  s.homepage = %q{http://github.com/ruby-bdb/sbdb}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{Simple Ruby Berkeley DB}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bdb>, [">= 0"])
    else
      s.add_dependency(%q<bdb>, [">= 0"])
    end
  else
    s.add_dependency(%q<bdb>, [">= 0"])
  end
end

